#!/bin/bash

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
WHITE_IP=192.168.10.10
WHITE_WIZNET=192.168.10.88
BLACK_IP=192.168.10.20
BLACK_WIZNET=192.168.10.89
unset WHITE_SERPENT
unset BLACK_SERPENT

# Begin by putting ourselves on a random IP address. 
TEST_IP=192.168.10.$(perl -e 'print 200+int(rand()*50)')
ifconfig usb0 up $TEST_IP

# Ping both Wiznet receivers.
rm -f /tmp/rtt.white /tmp/rtt.black
(ping -f -c 5 -w 1 $WHITE_WIZNET | grep / | sed -e 's/.*= //' -e 's+/.*++' > /tmp/rtt.white) &
(ping -f -c 5 -w 1 $BLACK_WIZNET | grep / | sed -e 's/.*= //' -e 's+/.*++' > /tmp/rtt.black) &

# Wait for at least one of them to respond.
sleep 0.5
while [ ! -s /tmp/rtt.white -a ! -s /tmp/rtt.black ]; do
  sleep 0.5
done

# Figure out which one is nearer (or present at all).
WHITE_RTT=$(cat /tmp/rtt.white)
BLACK_RTT=$(cat /tmp/rtt.black)
export SERPENT=$(perl -e "print ((('$WHITE_RTT' || 1e6) < ('$BLACK_RTT' || 1e6)) ? 'WHITE' : 'BLACK')")

# Set the IP address of the Wiznet receiver to use.
echo "WHITE_RTT=$WHITE_RTT, BLACK_RTT=$BLACK_RTT, SERPENT=$SERPENT"
if [ "$SERPENT" == "WHITE" ]; then
  echo "$WHITE_WIZNET 60666" > /tmp/serpent
  export WHITE_SERPENT=1
  LOCAL_IP=$WHITE_IP
else
  echo "$BLACK_WIZNET 60666" > /tmp/serpent
  export BLACK_SERPENT=1
  LOCAL_IP=$BLACK_IP
fi
echo
echo "Detected $SERPENT serpent, using $LOCAL_IP -> $(cat /tmp/serpent)."
echo
ifconfig usb0 up $LOCAL_IP
ifconfig usb0
echo

# Start the serpent program in a screen session.
cd /home/root/bin
echo "screen ./serpent" > /tmp/screenrc
ln -sf /dev/midi1 /tmp/midi.in
ln -sf /dev/midi1 /tmp/midi.out
echo -e '\x90\x10\x7f' > /tmp/midi.out
screen -dmS serpent -c /tmp/screenrc

