#!/bin/bash

# Run an animation on the Chumby.

CC=gcc
COPTS="-std=c99 -lm -O3"

name=${1%%.c}
if [ ! -d bin ]; then mkdir bin; fi

echo $CC $COPTS serpent_chumby.c total_control.c $name.c -o bin/$name && \
    $CC $COPTS serpent_chumby.c total_control.c $name.c -o bin/$name && \
    ls -al bin/$name
