#!/bin/bash

# Copyright 2011 Christopher De Vries and Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CC=gcc
if [ $(uname) == "Darwin" ]; then
  COPTS="-framework OpenGL -framework GLUT -std=c99"
else
  COPTS="-std=c99 -lGL -lGLU -lglut -lm"
fi

name=${1%%.c}
if [ ! -d build ]; then mkdir build; fi

echo $CC $COPTS serpent.c $name.c -o build/$name && \
    $CC $COPTS serpent.c $name.c -o build/$name && \
    echo build/$name && \
    build/$name
